#! /bin/zsh
#
# Written by Andrew Pensinger
# SEE LICENSE

module="macOS"

description="Module to setup dotfiles on macOS"

premodules=(homefs
            zsh
            emacs
            vim
            tmux)

function install {
}

function update {
}

function remove {
}

. $DOTFILE_DIR/util/module.subr.zsh
